// <auto-generated />
namespace PunjabiDialogueTalk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Dialogue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dialogue));
        
        string IMigrationMetadata.Id
        {
            get { return "201502070501305_Dialogue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
